#!/bin/sh
# CI gate self-test: the headless boot-check predicate (#21).
#
# ci/pipeline.sh:109 used to grep boot output for only
# "SCRIPT ERROR|SHADER ERROR|Parse Error|ERROR: Failed to" — none of which
# match "ERROR: WaveLevel:", so a level whose object ids starved, or whose
# SpawnPoint got deleted, or that grew past the sight shaders' wall slots,
# shipped with exit 0 and zero grep hits. This tests the predicate
# directly: BOOT_ERROR_PATTERN (ci/boot_error_pattern.sh — the same
# variable ci/pipeline.sh greps the boot log with, both at the pass/fail
# test and at the line that prints the offenders) must catch every real
# godot_error! prefix this project's engine node classes carry, and must
# NOT catch a real, unrelated Godot ERROR: line — the hard constraint that
# keeps this from becoming a catch-all `^ERROR:` and the cheapest gate in
# the pipeline flaky.
#
# Pure POSIX sh, no network, no Godot — runs anywhere ci/pipeline.sh does.
set -eu
DIR="$(cd "$(dirname "$0")/.." && pwd)"
FAIL=0

. "$DIR/ci/boot_error_pattern.sh"

ok() { echo "boot-error-gate: OK   $1"; }
bad() { echo "boot-error-gate: FAIL $1"; FAIL=1; }

must_catch() { # must_catch <label> <line>
  if printf '%s\n' "$2" | grep -qiE "$BOOT_ERROR_PATTERN"; then
    ok "$1"
  else
    bad "$1 (BOOT_ERROR_PATTERN did not match — this line would ship silently)"
  fi
}

must_not_catch() { # must_not_catch <label> <line>
  if printf '%s\n' "$2" | grep -qiE "$BOOT_ERROR_PATTERN"; then
    bad "$1 (BOOT_ERROR_PATTERN matched a benign line — the gate would go flaky)"
  else
    ok "$1"
  fi
}

# --- the three lines issue #21 named, hand-derived from the format
# strings in rust/src/nodes/level.rs (not generated by calling that code) ---
must_catch "id-starvation error is caught (level.rs:400)" \
  "ERROR: WaveLevel: 2 solid(s) could not take an id distinct from everything they touch — those seams will not draw. Spread the geometry or widen WORLD_OIDS."
must_catch "deleted-spawn error is caught (level.rs:337)" \
  "ERROR: WaveLevel: no SpawnPoint marker — the hero has nowhere to wake"
must_catch "wall-overflow error is caught (level.rs:423, MAXW=32)" \
  "ERROR: WaveLevel: 33 walls exceed the sight shaders' 32 slots — the rest stop occluding"

# --- every sibling class that refuses to boot half-wired rather than limp,
# captured verbatim from a real gdUnit4 run of this project:
# godot --headless --path game -s res://addons/gdUnit4/bin/GdUnitCmdTool.gd
#   --ignoreHeadlessMode -c -a tests
must_catch "WaveLevel materials/pulses injection error is caught (level.rs:140)" \
  "ERROR: WaveLevel: materials/pulses not injected — the level cannot be seen"
must_catch "WaveCat injection error is caught (cat.rs:103)" \
  "ERROR: WaveCat: pulses/data_mat not injected — cat disabled"
must_catch "SoundFan injection error is caught (fan.rs:103)" \
  "ERROR: SoundFan: pulses/data_mat not injected — fan disabled"
must_catch "SoundRadio injection error is caught (radio.rs:102)" \
  "ERROR: SoundRadio: pulses/data_mat not injected — radio disabled"
must_catch "UnseeingPlayer injection error is caught (player.rs:161)" \
  "ERROR: UnseeingPlayer: pulses not injected — physics disabled"
must_catch "hero_body injection error is caught (hero.rs:82 — snake_case, not \"HeroBody:\")" \
  "ERROR: hero_body: player/camera not injected"

# --- the patterns this gate already caught before #21, which must keep
# catching — a real SCRIPT ERROR line, captured from a genuinely broken
# boot (game/.godot wiped mid-run, so the GDExtension classes were not yet
# registered when the scripts parsed) ---
must_catch "a SCRIPT ERROR still catches" \
  'SCRIPT ERROR: Parse Error: Could not find type "Pulses" in the current scope.'
must_catch "a bare ERROR: Failed to still catches" \
  'ERROR: Failed to load script "res://scripts/main.gd" with error "Parse error".'

# --- benign ERROR: lines that must NOT trip the gate ---
# Real, captured from the same gdUnit4 run cited above: WaveCore's
# REFUSAL_MESSAGE (rust/src/pulse_pool.rs) deliberately keeps pulses.gd's
# legacy text — "Pulses.emit:", not a registered class name — byte for
# byte, and a single refused wave request does not mean the level shipped
# broken the way a starved object id or a missing spawn point does.
must_not_catch "WaveCore's refusal message carries no class prefix, so it is not caught" \
  "ERROR: Pulses.emit: speed and max_r must be positive — wave refused"
# Synthetic canary, not captured from a real run: proves BOOT_ERROR_PATTERN
# is not secretly a catch-all "^ERROR:" — an arbitrary engine ERROR: line
# unrelated to any of our classes must pass through untouched.
must_not_catch "an arbitrary unrelated ERROR: line is not a catch-all hit" \
  "ERROR: NotAnEngineClass: this line exists only to prove the gate is not a bare catch-all"
# Well-known Godot *engine* ERROR: formats (Core's ERR_FAIL_COND-family
# macros) — not captured from this project's own boot (which is clean on
# every machine tried so far, see the report), but real, documented Godot
# core text, covering the Linux/droplet engine chatter neither this
# machine nor the reviewer's could reproduce.
must_not_catch "a Godot ERR_FAIL_COND-style condition line is not caught" \
  'ERROR: Condition "p_size.x < 0" is true.'
must_not_catch "a Godot resource-loader ERROR: line is not caught" \
  "ERROR: Cannot open file 'res://nonexistent.tres'."

# --- derived: every godot_error! prefix under rust/src/ must be covered
# by BOOT_ERROR_PATTERN, so a brand-new engine node class (a SoundBell
# tomorrow, say, with its own godot_error!("SoundBell: ...")) cannot
# boot-check silently the way #21 itself did. The must_catch literals
# above and BOOT_ERROR_PATTERN are both hand-copied from rust/src/, so
# they can go stale together and stay green together; this section closes
# that gap by reading rust/src/ directly instead of trusting a second copy
# of the same names.
#
# ffi.rs:234 is the one documented, pinned exception: WaveCore's
# REFUSAL_MESSAGE (rust/src/pulse_pool.rs) deliberately carries no class
# prefix at all (see ci/boot_error_pattern.sh). Pinning it by exact
# file:line means a NEW prefix-less godot_error! elsewhere in the tree is
# NOT silently forgiven by the same exception — it shows up below as "no
# Prefix: literal found" instead of vanishing.
SITES="$(grep -rn 'godot_error!' "$DIR/rust/src/" | grep -oE '^[^:]+:[0-9]+')"
if [ -z "$SITES" ]; then
  bad "found zero godot_error! call sites under rust/src/ — the extraction below is broken"
fi

EXCEPTION_SEEN=0
CHECKED=0
UNCOVERED=0
for site in $SITES; do
  case "$site" in
  */ffi.rs:234)
    EXCEPTION_SEEN=1
    continue
    ;;
  esac
  ERR_FILE="${site%:*}"
  ERR_LINE="${site##*:}"
  # the message string sits on this line for most call sites, but three of
  # the five WaveLevel ones open the macro on one line and quote the
  # message on the next — read both and take the first quoted prefix.
  MSG="$(sed -n "${ERR_LINE},$((ERR_LINE + 1))p" "$ERR_FILE")"
  PREFIX="$(printf '%s\n' "$MSG" | grep -oE '"[A-Za-z_]+:' | head -1 | tr -d '":')"
  if [ -z "$PREFIX" ]; then
    bad "godot_error! at $site has no \"Prefix: ...\" literal and is not the documented ffi.rs:234 exception"
    continue
  fi
  CHECKED=$((CHECKED + 1))
  if ! printf '%s\n' "ERROR: $PREFIX: probe" | grep -qiE "$BOOT_ERROR_PATTERN"; then
    UNCOVERED=$((UNCOVERED + 1))
    bad "rust/src/ emits \"ERROR: $PREFIX:\" at $site but BOOT_ERROR_PATTERN does not cover it — this class would boot-check silently"
  fi
done

if [ "$EXCEPTION_SEEN" -eq 1 ]; then
  ok "ffi.rs:234 (WaveCore's REFUSAL_MESSAGE) is present and is the one documented prefix-less exception"
else
  bad "ffi.rs:234 exception site not found — REFUSAL_MESSAGE's call site moved; update the exception pin"
fi

if [ "$UNCOVERED" -eq 0 ]; then
  ok "every godot_error! prefix under rust/src/ ($CHECKED checked) is covered by BOOT_ERROR_PATTERN"
fi

exit "$FAIL"
