#!/bin/sh
# CI gate self-test: the headless boot-check predicate (#21).
#
# ci/pipeline.sh:109 used to grep boot output for only
# "SCRIPT ERROR|SHADER ERROR|Parse Error|ERROR: Failed to" — none of which
# match "ERROR: WaveLevel:", so a level whose superface classes starved, or
# whose typed WaveSpawn got deleted, or that grew past the sight shaders' wall slots,
# shipped with exit 0 and zero grep hits. This tests the predicate
# directly: BOOT_ERROR_PATTERN (ci/boot_error_pattern.sh — the same
# variable ci/pipeline.sh greps the boot log with, both at the pass/fail
# test and at the line that prints the offenders) must catch every real
# godot_error! prefix this project's engine node classes carry, and must
# NOT catch a real, unrelated Godot ERROR: line — the hard constraint that
# keeps this from becoming a catch-all `^ERROR:` and the cheapest gate in
# the pipeline flaky.
#
# The derived half of that used to read the macro SITES and pull a
# "Prefix: " literal off each one, which held only while every message was
# written at its own godot_error!. The two-layer rule then moved the words
# where they belong — built in the pure, cargo-testable module, with the
# node merely saying them out loud — and four sites became
# godot_error!("{}", complaint) with no literal to read. The unit here is
# therefore the message TEXT, wherever it is written: what each macro puts
# at the head of its own message, plus a census of every class-style
# opening in the tree, plus a ban on conjuring one out of an interpolation.
# A macro that writes no leading text is a RELAY and vouches for nothing —
# it is the census that vouches for it, which is why the census may not be
# skipped, softened, or allowed to read nothing.
#
# Pure POSIX sh, no network, no Godot — runs anywhere ci/pipeline.sh does.
set -eu
DIR="$(cd "$(dirname "$0")/.." && pwd)"
# The tree the derived half reads, relative to $DIR. Overridable for one
# reason only: so this script can run ITSELF against a planted copy and
# prove it goes red — see the composition probe at the bottom.
SRC="${BOOT_GATE_SRC:-rust/src}"
FAIL=0

. "$DIR/ci/boot_error_pattern.sh"

ok() { echo "boot-error-gate: OK   $1"; }
bad() { echo "boot-error-gate: FAIL $1"; FAIL=1; }

must_catch() { # must_catch <label> <line>
  if printf '%s\n' "$2" | grep -qiE "$BOOT_ERROR_PATTERN"; then
    ok "$1"
  else
    bad "$1 (BOOT_ERROR_PATTERN did not match — this line would ship silently)"
  fi
}

must_not_catch() { # must_not_catch <label> <line>
  if printf '%s\n' "$2" | grep -qiE "$BOOT_ERROR_PATTERN"; then
    bad "$1 (BOOT_ERROR_PATTERN matched a benign line — the gate would go flaky)"
  else
    ok "$1"
  fi
}

# --- the three lines issue #21 named, hand-derived from the format
# strings in rust/src/nodes/level.rs (not generated by calling that code) ---
must_catch "superface-starvation error is caught" \
  "ERROR: WaveLevel: 2 superface class(es) could not take a label distinct from everything they touch — those seams will not draw. Spread the geometry or widen WORLD_OIDS."
must_catch "deleted typed-spawn error is caught" \
  "ERROR: WaveLevel: no WaveSpawn stands under the level — the hero has nowhere to wake, so the level origin is being used as a fallback. Add exactly one WaveSpawn."
must_catch "wall-overflow error is caught (level.rs:423, MAXW=32)" \
  "ERROR: WaveLevel: 33 walls exceed the sight shaders' 32 slots — the rest stop occluding"

# --- every sibling class that refuses to boot half-wired rather than limp,
# captured verbatim from a real gdUnit4 run of this project:
# godot --headless --path game -s res://addons/gdUnit4/bin/GdUnitCmdTool.gd
#   --ignoreHeadlessMode -c -a tests
must_catch "WaveLevel materials/pulses injection error is caught (level.rs:140)" \
  "ERROR: WaveLevel: materials/pulses not injected — the level cannot be seen"
must_catch "WaveCat injection error is caught (cat.rs:103)" \
  "ERROR: WaveCat: pulses/data_mat not injected — cat disabled"
must_catch "SoundFan injection error is caught (fan.rs:103)" \
  "ERROR: SoundFan: pulses/data_mat not injected — fan disabled"
must_catch "SoundRadio injection error is caught (radio.rs:102)" \
  "ERROR: SoundRadio: pulses/data_mat not injected — radio disabled"
must_catch "UnseeingPlayer injection error is caught (player.rs:161)" \
  "ERROR: UnseeingPlayer: pulses not injected — physics disabled"
must_catch "hero_body injection error is caught (hero.rs:82 — snake_case, not \"HeroBody:\")" \
  "ERROR: hero_body: player/camera not injected"
must_catch "WaveRun diagnostics are covered before their volume ever rises" \
  "ERROR: WaveRun: diagonal endpoints folded onto the dominant X axis"

# --- the patterns this gate already caught before #21, which must keep
# catching — a real SCRIPT ERROR line, captured from a genuinely broken
# boot (game/.godot wiped mid-run, so the GDExtension classes were not yet
# registered when the scripts parsed) ---
must_catch "a SCRIPT ERROR still catches" \
  'SCRIPT ERROR: Parse Error: Could not find type "Pulses" in the current scope.'
must_catch "a bare ERROR: Failed to still catches" \
  'ERROR: Failed to load script "res://scripts/main.gd" with error "Parse error".'

# --- benign ERROR: lines that must NOT trip the gate ---
# Real, captured from the same gdUnit4 run cited above: WaveCore's
# REFUSAL_MESSAGE (rust/src/pulse_pool.rs) deliberately keeps pulses.gd's
# legacy text — "Pulses.emit:", not a registered class name — byte for
# byte, and a single refused wave request does not mean the level shipped
# broken the way a starved superface class or a missing typed spawn does.
must_not_catch "WaveCore's refusal message carries no class prefix, so it is not caught" \
  "ERROR: Pulses.emit: speed and max_r must be positive — wave refused"
# Synthetic canary, not captured from a real run: proves BOOT_ERROR_PATTERN
# is not secretly a catch-all "^ERROR:" — an arbitrary engine ERROR: line
# unrelated to any of our classes must pass through untouched.
must_not_catch "an arbitrary unrelated ERROR: line is not a catch-all hit" \
  "ERROR: NotAnEngineClass: this line exists only to prove the gate is not a bare catch-all"
# Well-known Godot *engine* ERROR: formats (Core's ERR_FAIL_COND-family
# macros) — not captured from this project's own boot (which is clean on
# every machine tried so far, see the report), but real, documented Godot
# core text, covering the Linux/droplet engine chatter neither this
# machine nor the reviewer's could reproduce.
must_not_catch "a Godot ERR_FAIL_COND-style condition line is not caught" \
  'ERROR: Condition "p_size.x < 0" is true.'
must_not_catch "a Godot resource-loader ERROR: line is not caught" \
  "ERROR: Cannot open file 'res://nonexistent.tres'."

# --- the three readers ---
# What Godot prints is "ERROR: " followed by the formatted message, and
# BOOT_ERROR_PATTERN is a list of the openings that message is allowed to
# have. So the readers below answer the same question in the message's own
# currency — leading TEXT — rather than in a guessed-at "prefix" abstraction
# that only held while every message was a literal at its macro.

# The text a macro at <file>:<line> puts at the head of its own message:
# everything from its first string literal up to the first interpolation,
# line continuation or closing quote. An EMPTY head is the interesting
# answer — it means the macro writes no leading text at all and RELAYS a
# message built elsewhere, which is the two-layer shape this project asks
# for (the decision, and its words, live in the pure cargo-tested module;
# the node only says it out loud).
#
# The three truncations are three expressions rather than one bracket
# expression: `[{"\]` would be a backslash inside a bracket, where POSIX
# says literal and GNU sed claims escapes as an extension. Cutting at the
# first of each in turn lands on the earliest of the three either way, and
# needs nothing from sed that both implementations agree on.
literal_head() { # literal_head <file> <line>
  sed -n "$2,$(($2 + 1))p" "$1" | tr '\n' ' ' | sed -n 's/^[^"]*"//p' |
    sed -e 's/{.*$//' -e 's/".*$//' -e 's/\\.*$//'
}

# Every class-style diagnostic opening in <dir>, wherever it is written: a
# string literal beginning with an identifier followed by ": " ("WaveLevel:
# …") or by a quoted node name ("WaveWall '…': …") — the two shapes this
# project's engine classes actually use. Prints "<prefix> <file>:<line>".
#
# This is the reader that sees an opening built in a pure module, and it is
# what makes a relayed godot_error! provable instead of merely plausible.
#
# It censuses godot_warn! openings too, and that is deliberate. Telling the
# volumes apart needs a positional guess at which macro owns a literal, and
# that guess is defeated by one line of prose: a comment reading "fatal, not
# a godot_warn!" written above a format! excludes the very literal below it,
# and the class ships unseen. A gate a comment can switch off is not a gate.
# Nor would it be sound where it worked — level.rs:765-766 sends ONE
# level_plan Budget text to BOTH volumes, so a literal in a pure module
# cannot honestly be attributed to one of them. The rule is therefore flat:
# an engine class that names itself in a diagnostic belongs in
# BOOT_ERROR_PATTERN, whatever volume it happens to say it at today. That
# costs entries for WaveWall and WaveRun, which only warn — and buys their
# coverage the day it starts erroring.
#
# The colon form requires the SPACE after it. Without that, "res://…"
# censuses as a class called "res" and every resource path in the tree is a
# failure. Measured: requiring the space drops none of the 36 real openings.
diagnostic_census() { # diagnostic_census <dir>
  grep -rnoE '"[A-Za-z_][A-Za-z0-9_.]*(: | '\'')' "$1" |
    sed 's/^\([^:]*\):\([0-9][0-9]*\):"\([A-Za-z_][A-Za-z0-9_.]*\).*$/\3 \1:\2/'
}

# Messages that build their opening token out of an interpolation —
# format!("{cls}: …") or format!("{cls} '…'"). No census can read those, so
# they are banned outright rather than chased: this is the assumption the
# census rests on, checked instead of assumed.
#
# Scoped to a message macro's FIRST argument on purpose. The bare shape
# appears all over ordinary Rust — `assert_eq!(got, want, "{case}: the plan
# disagreed")` is idiomatic, has nothing to do with Godot's log, and a gate
# that reddens on it teaches its reader to stop believing it. What matters
# here is a message whose OPENING is conjured, and that only happens where
# the literal opens the call.
#
# The list is every macro that BUILDS a message, not the three that came to
# mind first: write!, writeln! and format_args! take the same format string
# and produce the same String, and naming only format! left three doors open
# in the one check the census leans on. rust/src holds zero of them today, so
# widening this cannot false-positive — it is pure insurance, which is the
# only sensible thing for the assumption everything else rests on.
#
# Two greps because "the format string" is not always the first argument:
# write! and writeln! take the destination first. Widening the first pattern
# to allow anything before the literal would have re-admitted assert_eq!'s
# message, which is the false positive this scoping exists to avoid.
synthesised_prefixes() { # synthesised_prefixes <dir>
  grep -rnE '(format!|format_args!|godot_error!|godot_warn!)\("\{[^"{}]*\}(: | '\'')' "$1" || true
  grep -rnE '(write!|writeln!)\([^,"]*, *"\{[^"{}]*\}(: | '\'')' "$1" || true
}

# The verdict on a census (read from stdin): every opening the boot check
# would NOT catch, minus the documented exception in the file that owns it.
#
# Forgiveness is by (prefix, home file) and is not rationed within that
# file. Rationing it to one read well and was wrong: this project's test
# doctrine says hand-derive the literal rather than mirror the code, so
# `assert_eq!(REFUSAL_MESSAGE, "Pulses.emit: …")` in pulse_pool.rs's own
# test module is exactly what a good test looks like here — and a second
# copy of the same legacy message in the file that owns it is not a new
# class sneaking in. What must never be forgiven is a DIFFERENT opening, or
# this one anywhere else, and both are still reported.
uncovered_openings() { # uncovered_openings <exception-prefix> <exception-home>
  while read -r prefix at; do
    [ -n "$prefix" ] || continue
    if [ "$prefix" = "$1" ] && [ "${at%:*}" = "$2" ]; then
      continue
    fi
    if printf '%s\n' "ERROR: $prefix" | grep -qiE "$BOOT_ERROR_PATTERN"; then
      continue
    fi
    printf '%s %s\n' "$prefix" "$at"
  done
}

# The second documented category (issue #64's fix-2): request-scoped
# refusals. Not a boot or composition failure — a malformed per-request
# wave/reflection/tick input, or a hero body not yet built at restore time
# — so it must never join BOOT_ERROR_PATTERN (ci/boot_error_pattern.sh
# argues at length against widening that pattern, and this fix does not
# reopen that argument). But it must also never be forgiven by inference —
# "anything under ffi.rs", "any opening with a dot" — because that would
# silently swallow the next real boot-failure class introduced there. So:
# an ENUMERATED table of (opening, home file) pairs, read off the actual
# source at the time each was reviewed. ci/boot_error_pattern.sh's header
# names the same four as the documentation of record; this table is where
# the gate actually enforces it, so keep the two in step by hand.
REQUEST_REFUSALS="WaveCore.emit_reflecting $SRC/ffi.rs
WaveCore.tick $SRC/ffi.rs
Pulses.emit $SRC/ffi.rs
hero.viewmodel $SRC/nodes/restorer.rs"

# Drop from a census (stdin, one "<prefix> <file>:<line>" per line) every
# line whose (prefix, home file) pair appears in <table> (arg 1, the same
# "prefix home" shape as REQUEST_REFUSALS above, one pair per line).
# Deliberately its own function rather than a second exception folded into
# uncovered_openings: that keeps the ONE legacy Pulses.emit/pulse_pool.rs
# exception — with its own stricter pin on the exact message text and the
# single emitter count below — provably untouched by this table, rather
# than merged into one rule neither test could pin on its own. Bound the
# same way as that legacy exception even so: prefix AND home together, so
# the same prefix opened from a file that is not its enumerated home is
# left for uncovered_openings (or a human) to report like anything else.
strip_request_refusals() { # strip_request_refusals <table>
  table="$1"
  while read -r prefix at; do
    [ -n "$prefix" ] || continue
    home="${at%:*}"
    hit=0
    while read -r r_prefix r_home; do
      [ -n "$r_prefix" ] || continue
      if [ "$prefix" = "$r_prefix" ] && [ "$home" = "$r_home" ]; then
        hit=1
        break
      fi
    done <<REQUEST_TABLE_EOF
$table
REQUEST_TABLE_EOF
    [ "$hit" = 1 ] && continue
    printf '%s %s\n' "$prefix" "$at"
  done
}

# --- the readers' own fixtures ---
# Everything below this line reads rust/src/ and reports what it found
# there, so a reader that has quietly stopped matching reports an empty
# tree and passes. These run those same readers over a synthetic file
# whose every answer is written out by hand, so a broken regex fails HERE,
# by name, instead of going vacuously green down there.
FIX="$(mktemp -d)"
trap 'rm -rf "$FIX"' EXIT INT TERM
cat >"$FIX/fixture.rs" <<'FIXTURE'
// a node class that names itself at the macro site
godot_error!("SoundBell: the bell will not ring");
// the same, opened on one line and quoted on the next
godot_error!(
    "SoundBell: {} of {} bells are silent",
    dead, all
);
// a COVERED class, so a reader that found nothing cannot pass as a reader
godot_error!("WaveLevel: materials/pulses not injected");
// the two-layer relay: the macro contributes no leading text of its own
godot_error!("{}", complaint);
// a relay of a named constant
godot_error!("{REFUSAL_MESSAGE}");
// the pure module that builds the message that relay carries
let complaint = format!("SoundBell: {} rang out of turn", name);
// a class naming a node before its colon, at a WARNING — censused all the same
godot_warn!(
    "SoundBell '{}': hung crooked",
    name
);
// ordinary strings, not diagnostics at all
let key = "u_wall_count";
let why = "the bell has no clapper";
// a message that SYNTHESISES its opening token
let bad = format!("{cls}: no census can read this");
// a class that names a node before its colon, this time bound for an ERROR
let cracked = format!("SoundGong '{}': cracked clean through", name);
// a message wrapped onto the next line with a continuation
godot_error!(
    "SoundBell: the rope is too short \
     to reach the bell"
);
// a resource path: it opens exactly like a class if the space is forgotten
let scene = load::<PackedScene>("res://scenes/bell.tscn");
// a synthesised opening that is NOT a message macro's first argument
assert_eq!(got, want, "{case}: the plan disagreed");
// the same conjuring through the OTHER message builders — write! puts its
// destination first, so its format string is the second argument
write!(buf, "{cls}: built somewhere else entirely").ok();
format_args!("{cls} 'Bell': and by a third route");
FIXTURE

must_head() { # must_head <line> <expected head> <label>
  GOT="$(literal_head "$FIX/fixture.rs" "$1")"
  if [ "$GOT" = "$2" ]; then ok "$3"; else bad "$3 (read [$GOT], expected [$2])"; fi
}

must_head 2 "SoundBell: the bell will not ring" \
  "a one-line godot_error! yields its whole leading literal"
must_head 4 "SoundBell: " \
  "a macro quoted on the NEXT line still yields its head, truncated at the first {}"
must_head 9 "WaveLevel: materials/pulses not injected" \
  "a covered class yields its head too (a reader that returns nothing is not a reader)"
must_head 11 "" \
  'godot_error!("{}", x) yields an EMPTY head — it relays, it does not prefix'
must_head 13 "" \
  'godot_error!("{CONST}") yields an empty head as well'
must_head 29 "SoundBell: the rope is too short " \
  "a head stops at the line continuation rather than running into the next line"

CENSUS_FIX="$(diagnostic_census "$FIX")"
must_census() { # must_census <prefix> <line> <label>
  if printf '%s\n' "$CENSUS_FIX" | grep -q "^$1 .*fixture\.rs:$2\$"; then
    ok "$3"
  else
    bad "$3 (census missed it — the SoundBell it cannot see is the one that ships)"
  fi
}
must_not_census() { # must_not_census <line> <label>
  if printf '%s\n' "$CENSUS_FIX" | grep -q "fixture\.rs:$1\$"; then
    bad "$2 (census claimed a diagnostic prefix that is not one — it will go flaky)"
  else
    ok "$2"
  fi
}

must_census SoundBell 2 "census sees a prefix written at the macro"
must_census SoundBell 5 "census sees a prefix written one line below its macro"
must_census SoundBell 15 "census sees a prefix built in a PURE module — the whole point of this fix"
must_census SoundBell 18 "census sees a godot_warn!'s opening too — no adjacency guess a comment could defeat"
must_census SoundGong 27 "census sees a class that names a node before its colon, bound for an ERROR"
must_not_census 22 "a plain shader-parameter string is not mistaken for a diagnostic prefix"
must_not_census 23 "an ordinary sentence starting with a word is not mistaken for a class prefix"
must_not_census 25 "a SYNTHESISED opening is invisible to the census — which is exactly why it is banned outright"
must_not_census 34 "a res:// path is not censused as a class called \"res\" — this is what the colon's SPACE buys"

SYNTH_FIX="$(synthesised_prefixes "$FIX")"
if printf '%s\n' "$SYNTH_FIX" | grep -q 'fixture\.rs:25'; then
  ok "a message that builds its opening token out of an interpolation is flagged"
else
  bad "a synthesised opening token slipped past — the census is blind to it and so is the gate"
fi
if printf '%s\n' "$SYNTH_FIX" | grep -q 'fixture\.rs:36'; then
  bad "an assert_eq! message was flagged as a synthesised class opening — idiomatic Rust that cannot reach a boot log, and a gate that cries on it stops being read"
else
  ok "an interpolation opening a NON-first argument (assert_eq!'s message) is left alone"
fi
if printf '%s\n' "$SYNTH_FIX" | grep -q 'fixture\.rs:39'; then
  ok "write! conjuring an opening is flagged too — its format string is the SECOND argument and was a hole"
else
  bad "write! can still conjure a class opening — the census cannot read what it builds, and neither can this gate"
fi
if printf '%s\n' "$SYNTH_FIX" | grep -q 'fixture\.rs:40'; then
  ok "format_args! conjuring an opening is flagged too"
else
  bad "format_args! can still conjure a class opening — same message, same log, different macro"
fi

# The verdict, over a census written out by hand rather than read off this
# tree, so every branch of the exception is exercised — including the two
# that rust/src/ cannot show today because it holds exactly one legitimate
# exception and no violations.
VERDICT_GOT="$(uncovered_openings Pulses.emit rust/src/pulse_pool.rs <<'CENSUS_FIXTURE'
WaveLevel rust/src/nodes/level.rs:178
SoundBell rust/src/bell_plan.rs:12
Pulses.emit rust/src/nodes/stranger.rs:7
Pulses.emit rust/src/pulse_pool.rs:31
Pulses.emit rust/src/pulse_pool.rs:99
CENSUS_FIXTURE
)"
# The stranger carries the SAME prefix as the exception from a file that is
# not its home, which is what tells "forgiven by prefix" from "forgiven by
# prefix AND home" apart. The home file's second copy is forgiven on
# purpose: a hand-written pin for REFUSAL_MESSAGE in pulse_pool.rs's own
# test module is the anti-mirror form this project's doctrine asks for, and
# it must not redden the pipeline.
VERDICT_WANT="SoundBell rust/src/bell_plan.rs:12
Pulses.emit rust/src/nodes/stranger.rs:7"
if [ "$VERDICT_GOT" = "$VERDICT_WANT" ]; then
  ok "the verdict passes a covered class, reports an uncovered one, and spends the documented exception exactly ONCE and only in its own file"
else
  bad "the verdict misread its fixture — got [$VERDICT_GOT], expected [$VERDICT_WANT]"
fi

# strip_request_refusals's own fixture, over a hand-written table rather
# than the real REQUEST_REFUSALS, so this proves the FUNCTION's logic —
# prefix AND home together — independent of whatever the real table holds
# today. Two things this must show that the legacy-exception test above
# does not: the same prefix survives from an unenumerated home (proving
# this is an enumeration, not "Pulses.emit is fine everywhere"), and an
# entry the OTHER mechanism already forgives (Pulses.emit in
# pulse_pool.rs) survives here too, because this function has never heard
# of it — the two forgiveness mechanisms stay provably separate.
STRIP_GOT="$(strip_request_refusals "WaveCore.emit_reflecting rust/src/ffi.rs
Pulses.emit rust/src/ffi.rs
hero.viewmodel rust/src/nodes/restorer.rs" <<'STRIP_FIXTURE'
WaveCore.emit_reflecting rust/src/ffi.rs:145
WaveCore.emit_reflecting rust/src/nodes/level.rs:9
Pulses.emit rust/src/ffi.rs:614
Pulses.emit rust/src/pulse_pool.rs:31
hero.viewmodel rust/src/nodes/restorer.rs:261
hero.viewmodel rust/src/nodes/observer.rs:5
SoundBell rust/src/bell_plan.rs:12
STRIP_FIXTURE
)"
STRIP_WANT="WaveCore.emit_reflecting rust/src/nodes/level.rs:9
Pulses.emit rust/src/pulse_pool.rs:31
hero.viewmodel rust/src/nodes/observer.rs:5
SoundBell rust/src/bell_plan.rs:12"
if [ "$STRIP_GOT" = "$STRIP_WANT" ]; then
  ok "strip_request_refusals drops every enumerated (prefix, home) pair and leaves everything else untouched — including the same prefix from an unenumerated home, and the legacy pulse_pool.rs exception it knows nothing about"
else
  bad "strip_request_refusals misread its fixture — got [$STRIP_GOT], expected [$STRIP_WANT]"
fi

# --- derived, and read four ways ---
# Reading the macro SITES alone stopped being enough the moment the message
# text moved where the two-layer rule wants it: built in the pure,
# cargo-testable module, with the node merely saying it out loud. The unit
# below is therefore the message TEXT, wherever it is written, and the
# question asked of it is the boot check's own: would
# ci/pipeline.sh's grep catch the line Godot prints? All four read rust/src/
# directly rather than trusting the hand-copied literals above, which can go
# stale together with BOOT_ERROR_PATTERN and stay green together.

# The one documented exception, and it is a PREFIX with a home, not a call
# site: WaveCore's REFUSAL_MESSAGE deliberately keeps pulses.gd's legacy
# "Pulses.emit:" text instead of a class name (see ci/boot_error_pattern.sh),
# and one refused wave request does not mean the level shipped broken the way
# a starved superface class does. Pinning the prefix AND the file that owns it is
# what keeps it a single exception rather than a category: a different
# opening, or this one anywhere else, is reported like any other violation.
#
# Defined here, above both readers that need it (SITES right below, CENSUS
# further down), because a literal head at its OWN call site can name this
# exact exception too — it is the CENSUS reader's forgiveness first, and
# the SITES reader below reaches for the same pair rather than growing a
# second copy of it.
EXCEPT_PREFIX="Pulses.emit"
EXCEPT_HOME="$SRC/pulse_pool.rs"

# The single (prefix, home) membership test both the legacy exception and
# the enumerated REQUEST_REFUSALS table answer to: forgiven iff the pair
# matches the legacy exception exactly, or matches one line of <table>
# exactly. Fully parameterised (nothing read off a global here) so its own
# fixture below can hand-derive every branch without depending on what
# EXCEPT_PREFIX/EXCEPT_HOME/REQUEST_REFUSALS happen to hold today. The
# CENSUS reader further down does NOT call this — it already has
# strip_request_refusals (the table) piped into uncovered_openings (the
# legacy exception) as two separately fixtured stages, and duplicating
# that here would be a second, divergeable copy of the same rule. This
# function exists so the SITES reader gets the identical two-stage answer
# without growing a third implementation of either stage.
pair_forgiven() { # pair_forgiven <prefix> <home> <legacy-prefix> <legacy-home> <table>
  [ "$1" = "$3" ] && [ "$2" = "$4" ] && return 0
  while read -r r_prefix r_home; do
    [ -n "$r_prefix" ] || continue
    [ "$1" = "$r_prefix" ] && [ "$2" = "$r_home" ] && return 0
  done <<PAIR_TABLE_EOF
$5
PAIR_TABLE_EOF
  return 1
}

# pair_forgiven's own fixture — hand-derived, not read off REQUEST_REFUSALS,
# so a mutation that drops the home half of either comparison (matching by
# prefix alone) fails HERE, fast, rather than only in a full-tree plant.
PF_LEGACY_P="Pulses.emit"
PF_LEGACY_H="rust/src/pulse_pool.rs"
PF_TABLE="WaveCore.tick rust/src/ffi.rs"
if pair_forgiven "$PF_LEGACY_P" "$PF_LEGACY_H" "$PF_LEGACY_P" "$PF_LEGACY_H" "$PF_TABLE"; then
  ok "pair_forgiven accepts the legacy exception's own (prefix, home)"
else
  bad "pair_forgiven rejected the legacy exception's own (prefix, home) — the SITES reader would report it as a NEW violation"
fi
if pair_forgiven "$PF_LEGACY_P" "rust/src/nodes/stranger.rs" "$PF_LEGACY_P" "$PF_LEGACY_H" "$PF_TABLE"; then
  bad "pair_forgiven accepted the legacy exception's PREFIX from a file that is not its home — the legacy exception has widened into a prefix-wide pass"
else
  ok "pair_forgiven rejects the legacy exception's prefix from an unenumerated home"
fi
if pair_forgiven "WaveCore.tick" "rust/src/ffi.rs" "$PF_LEGACY_P" "$PF_LEGACY_H" "$PF_TABLE"; then
  ok "pair_forgiven accepts an enumerated REQUEST_REFUSALS pair"
else
  bad "pair_forgiven rejected an enumerated REQUEST_REFUSALS pair — the SITES reader would report every one of them"
fi
if pair_forgiven "WaveCore.tick" "rust/src/nodes/level.rs" "$PF_LEGACY_P" "$PF_LEGACY_H" "$PF_TABLE"; then
  bad "pair_forgiven accepted an enumerated PREFIX from a file that is not its enumerated home — prefix-and-home binding is broken"
else
  ok "pair_forgiven rejects an enumerated prefix from a file that is not its enumerated home"
fi
if pair_forgiven "SoundBell" "rust/src/bell_plan.rs" "$PF_LEGACY_P" "$PF_LEGACY_H" "$PF_TABLE"; then
  bad "pair_forgiven accepted a prefix that appears in neither the legacy exception nor the table"
else
  ok "pair_forgiven rejects a prefix that is neither the legacy exception nor in the table"
fi

# (1) SITES — what each godot_error! writes at the head of its OWN message.
# "ERROR: <head>" goes to the same pattern ci/pipeline.sh greps the boot log
# with, so this is the real predicate on the real string rather than a proxy
# for it. It is strictly stronger than the "Prefix: " extraction it replaces,
# which could only see a class name followed by a colon and would have missed
# a godot_error!("WaveWall '{}': ...") entirely.
SITES="$(cd "$DIR" && grep -rn 'godot_error!' "$SRC" | grep -oE '^[^:]+:[0-9]+' || true)"
if [ -z "$SITES" ]; then
  bad "found zero godot_error! call sites under $SRC — the site reader is broken"
fi

HEADED=0
RELAYS=""
for site in $SITES; do
  HEAD="$(cd "$DIR" && literal_head "${site%:*}" "${site##*:}")"
  if [ -z "$HEAD" ]; then
    # (2) A RELAY. The macro writes no leading text, so the site itself can
    # vouch for nothing — and nothing is waved through on that account. What
    # answers for it is (3), which reads the literal where it was actually
    # written, and (4), which forbids conjuring one that was never written at
    # all. Printed by name: a relay nobody names is a relay nobody reviews.
    #
    # THE STANDING BLIND SPOT, stated as the family it is rather than the
    # one member that is easiest to picture: a relayed message is read here
    # only if its class token is the HEAD OF A SINGLE STRING LITERAL. Split
    # it and nothing reads it — "SoundBell".to_string() + ": no clapper",
    # concat!("SoundBell", ": no clapper"), s.push_str("SoundBell"), or a
    # message that simply opens some other way ("SoundBell rang twice").
    # Every one of those puts ERROR: SoundBell: … in the boot log with
    # nothing for the census to see. None of those idioms appears in
    # rust/src today — format! is universal here and every engine
    # diagnostic opens with its class name — but that is a habit, not a
    # law, and this is the seam it protects.
    RELAYS="$RELAYS $site"
    continue
  fi
  HEADED=$((HEADED + 1))
  if printf '%s\n' "ERROR: $HEAD" | grep -qiE "$BOOT_ERROR_PATTERN"; then
    continue
  fi
  # A literal head that does not match BOOT_ERROR_PATTERN directly may
  # still be an enumerated request-scoped refusal, or the one legacy
  # Pulses.emit exception — the SAME forgiveness the CENSUS reader further
  # down applies (via pair_forgiven, above), reached for here too because
  # a message written with its own leading text (rather than relayed from
  # a pure module) is seen by THIS reader first and must not be reported
  # as a second, different violation of the same fact.
  SITE_PREFIX="$(printf '%s' "$HEAD" | sed -n 's/^\([A-Za-z_][A-Za-z0-9_.]*\): .*$/\1/p')"
  if [ -z "$SITE_PREFIX" ]; then
    SITE_PREFIX="$(printf '%s' "$HEAD" | sed -n 's/^\([A-Za-z_][A-Za-z0-9_.]*\) '\''.*$/\1/p')"
  fi
  SITE_HOME="${site%:*}"
  if [ -n "$SITE_PREFIX" ] &&
    pair_forgiven "$SITE_PREFIX" "$SITE_HOME" "$EXCEPT_PREFIX" "$EXCEPT_HOME" "$REQUEST_REFUSALS"; then
    continue
  fi
  bad "$SRC prints \"ERROR: $HEAD\" at $site and BOOT_ERROR_PATTERN does not catch it — this class would boot-check silently"
done

if [ "$HEADED" -gt 0 ]; then
  ok "every godot_error! that writes its own leading text ($HEADED of them) prints a line BOOT_ERROR_PATTERN catches"
else
  bad "not one godot_error! under $SRC was read as writing leading text — literal_head has stopped reading"
fi
if [ -n "$RELAYS" ]; then
  # Deliberately NOT "vouched for". The census reads every CLASS-STYLE
  # opening in the tree, so a relay carrying one is answered for; a relay
  # carrying a message that opens some other way — "SoundBell rang twice" —
  # is read by neither reader and is this gate's standing blind spot. It is
  # narrow (every engine diagnostic in this tree opens "Class: " or
  # "Class '") but it is real, and the honest word for it is not "vouched".
  ok "relayed from elsewhere, so answered for by the census below, not by the site:$RELAYS"
fi

# (3) CENSUS — every class-style diagnostic opening in the tree, wherever it
# is written, must be one BOOT_ERROR_PATTERN catches. This is the check that
# sees the next SoundBell: a format!("SoundBell: …") in a pure module is red
# here even though not one macro site mentions the name.
CENSUS="$(cd "$DIR" && diagnostic_census "$SRC")"

if [ -z "$CENSUS" ]; then
  bad "the census read zero class-style openings out of $SRC — diagnostic_census has stopped reading"
else
  CENSUSED="$(printf '%s\n' "$CENSUS" | grep -c . || true)"
  # Reading the right tree is a separate claim from reading it correctly,
  # and only the second one has fixtures. Aim the census at $SRC/nodes and
  # it still reads perfectly — it just stops seeing every opening built in
  # a pure module, which is the entire reason this check exists. So assert
  # the census actually reached outside the node classes. Stated as the
  # directory rather than as a filename: naming level_plan.rs would redden
  # this gate the day that file is renamed, for a reason having nothing to
  # do with boot errors.
  if printf '%s\n' "$CENSUS" | grep -Fv " $SRC/nodes/" | grep -q .; then
    ok "the census reached past the node classes into the pure modules ($CENSUSED openings)"
  else
    bad "the census read $CENSUSED openings and every one of them is under $SRC/nodes/ — it is aimed too narrowly, and every opening built in a pure module is invisible to it"
  fi

  UNCOVERED="$(printf '%s\n' "$CENSUS" | strip_request_refusals "$REQUEST_REFUSALS" |
    uncovered_openings "$EXCEPT_PREFIX" "$EXCEPT_HOME")"
  if [ -z "$UNCOVERED" ]; then
    ok "every class-style opening under $SRC prints a line BOOT_ERROR_PATTERN catches, bar the forgiven \"$EXCEPT_PREFIX\" in $EXCEPT_HOME and the enumerated request-scoped refusals"
  else
    # Fed by here-doc, not by a pipe: down a pipe `bad` would set FAIL in a
    # subshell that then exits, and this whole half would print its failures
    # and return 0. ci/pipeline.sh reads the exit code and nothing else.
    while read -r prefix at; do
      [ -n "$prefix" ] || continue
      bad "$at opens messages with \"$prefix\" and BOOT_ERROR_PATTERN does not catch \"ERROR: $prefix\" — that class would boot-check silently"
    done <<UNCOVERED_EOF
$UNCOVERED
UNCOVERED_EOF
  fi
fi

# What the forgiveness actually covers: ONE message, not a prefix anyone may
# borrow. Without this, a new const in pulse_pool.rs reading "Pulses.emit:
# SoundBell has no clapper", emitted from a node, is waved straight through
# — and the line below would still have announced a single emitter, because
# it counts the IDENTIFIER REFUSAL_MESSAGE rather than the opening the log
# actually carries. A printed claim outrunning its assertion is the exact
# defect the census was built to stop; it does not get to live here.
#
# The pinned text is a second copy of pulse_pool.rs's const, deliberately,
# in the same spirit as the hand-copied must_catch lines above: if the const
# is reworded this goes red asking to be re-pinned, rather than quietly
# widening to whatever the const now says.
EXCEPT_TEXT="Pulses.emit: speed and max_r must be positive — wave refused"
FORGIVEN=0
while read -r prefix at; do
  [ "$prefix" = "$EXCEPT_PREFIX" ] || continue
  [ "${at%:*}" = "$EXCEPT_HOME" ] || continue
  FORGIVEN=$((FORGIVEN + 1))
  TEXT="$(cd "$DIR" && literal_head "${at%:*}" "${at##*:}")"
  if [ "$TEXT" != "$EXCEPT_TEXT" ]; then
    bad "$at opens \"$EXCEPT_PREFIX\" but says \"$TEXT\" — the forgiveness covers the one legacy refusal message, not a prefix a new message may wear to get past this gate"
  fi
done <<FORGIVEN_EOF
$CENSUS
FORGIVEN_EOF

# And the call site, which is a different claim from the opening and is
# still singular: one identifier, one macro, one way to the log. Counted
# rather than pinned to a line number — the old `sed -n '234p'` pin broke on
# any edit above it and never tested this at all.
EXCEPT_EMITTERS="$(cd "$DIR" && grep -rn 'godot_error!.*REFUSAL_MESSAGE' "$SRC" | grep -c . || true)"
if [ "$EXCEPT_EMITTERS" = "1" ]; then
  ok "the forgiveness covers $FORGIVEN written copies of ONE legacy message in $EXCEPT_HOME, and the REFUSAL_MESSAGE const reaches the log from exactly one macro"
else
  bad "REFUSAL_MESSAGE is emitted from $EXCEPT_EMITTERS macros, not 1 — a message BOOT_ERROR_PATTERN deliberately ignores has grown a second way to the boot log"
fi

# (4) No message may build its opening token out of an interpolation. The
# census reads literals; a format!("{cls}: …") would be invisible to it, and
# a relay carrying one would print a class name nobody ever wrote down. This
# is the assumption (3) rests on, checked rather than hoped for.
SYNTH="$(cd "$DIR" && synthesised_prefixes "$SRC")"
if [ -z "$SYNTH" ]; then
  ok "no message under $SRC builds its opening token out of an interpolation — every class name is a literal the census can read"
else
  bad "a message builds its opening token out of an interpolation, so no census can read it: $(printf '%s' "$SYNTH" | tr '\n' ' ')"
fi

# --- the composition's own probe ---
# Everything above is checked in parts: the readers by fixtures, the pattern
# by hand-written lines. The parts have been right and the WHOLE still a
# no-op — an exclusion driven by comment text, a census aimed at the wrong
# directory, a verdict whose failure flag died in a subshell. Each of those
# left every assertion above green.
#
# So: copy the real tree, plant in it exactly the thing this gate exists to
# stop — a class BOOT_ERROR_PATTERN has never heard of, its message built in
# a pure module and relayed by a node, in the two-layer shape the project
# asks for — and run THIS SCRIPT against the copy. Green there is a broken
# gate no matter how many OKs precede it. The clean copy runs first, so a
# red from the plant is the plant and not the copying.
#
# Precisely what this proves, since the honest scope is narrower than "end
# to end" suggests: the chain census -> verdict -> FAIL -> exit code, over
# the real tree's shape and size. The relay half of the plant is there to
# make it the realistic two-layer shape, not because the red depends on it
# — the pure-module literal alone is already red. Relay HANDLING is covered
# by the site fixtures, not here.
#
# $SRC is what makes this possible and it exists for nothing else.
if [ -z "${BOOT_GATE_SRC:-}" ]; then
  cp -R "$DIR/$SRC" "$FIX/clean"
  if (BOOT_GATE_SRC="$FIX/clean" sh "$0" >/dev/null 2>&1); then
    ok "an untouched copy of $SRC still passes — so the red below is the plant, not the copy"
  else
    bad "an untouched copy of $SRC does NOT pass, so the plant below proves nothing — fix this first"
  fi

  cp -R "$DIR/$SRC" "$FIX/planted"
  # NotAnEngineClass rather than SoundBell: the day a SoundBell really ships
  # and joins BOOT_ERROR_PATTERN, this probe must not quietly stop probing.
  # The comment above the format! is not decoration — mentioning godot_warn!
  # next to a literal once excluded it from the census, and this pins that
  # shut.
  cat >>"$FIX/planted/level_plan.rs" <<'PLANT'

/// Fatal, not a godot_warn!: a class the boot pattern has never heard of.
pub fn planted_complaint(n: u32) -> String {
    format!("NotAnEngineClass: {n} of them, and none of them draw")
}
PLANT
  cat >>"$FIX/planted/nodes/level.rs" <<'PLANT'
// the two-layer relay: the words are the pure module's, the voice is here
fn planted_say() {
    godot_error!("{}", level_plan::planted_complaint(2));
}
PLANT
  if (BOOT_GATE_SRC="$FIX/planted" sh "$0" >/dev/null 2>&1); then
    bad "a NotAnEngineClass built in a pure module and relayed by a node did NOT turn this gate red — the derived half above is decorative"
  else
    ok "a class built in a pure module and relayed by a node turns this gate red, end to end — the composition works, not just the parts"
  fi

  # Two more compositions this project's issue #64 fix-2 must not become a
  # hole for: the request-scoped-refusal category is an ENUMERATED table,
  # not "anything in an enumerated file" and not "this opening, anywhere".
  # Both plants live in ffi.rs itself — the enumerated home of three of the
  # four table entries — precisely because that is where a blanket
  # would-be exemption would be easiest to mistake for correct.

  cp -R "$DIR/$SRC" "$FIX/request_unlisted"
  # A request-scoped-shaped refusal ("WaveCore....: ...") that nobody has
  # reviewed and added to REQUEST_REFUSALS. If ffi.rs itself were forgiven
  # wholesale, this would vanish; it must not.
  cat >>"$FIX/request_unlisted/ffi.rs" <<'PLANT'

/// A request refusal this campaign never reviewed or enumerated.
fn planted_unlisted_refusal() -> String {
    "WaveCore.unlisted_refusal: this reason was never enumerated — refused".to_string()
}
PLANT
  if (BOOT_GATE_SRC="$FIX/request_unlisted" sh "$0" >/dev/null 2>&1); then
    bad "a request-scoped refusal opening NOT in REQUEST_REFUSALS did not turn this gate red, even written in an enumerated home file — the category has widened into a free pass for the file instead of staying a table"
  else
    ok "an unenumerated request-refusal opening turns this gate red even from inside an enumerated home file — the category is a table, not a file-wide exemption"
  fi

  cp -R "$DIR/$SRC" "$FIX/request_wrong_home"
  # An ENUMERATED opening ("hero.viewmodel"), planted outside its one
  # enumerated home (rust/src/nodes/restorer.rs). If forgiveness followed
  # the prefix alone, this would vanish too; it must not.
  cat >>"$FIX/request_wrong_home/nodes/level.rs" <<'PLANT'

/// The enumerated opening "hero.viewmodel", said from a file that is not
/// its one enumerated home.
fn planted_wrong_home() -> String {
    "hero.viewmodel: planted outside its enumerated home".to_string()
}
PLANT
  if (BOOT_GATE_SRC="$FIX/request_wrong_home" sh "$0" >/dev/null 2>&1); then
    bad "the enumerated opening \"hero.viewmodel\" planted outside restorer.rs did NOT turn this gate red — the new category is forgiving the prefix alone, not prefix AND home"
  else
    ok "an enumerated request-refusal opening planted outside its one home file still turns this gate red — prefix-and-home binding holds for the new category too"
  fi
fi

exit "$FAIL"
